# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
          release-notes.yml
      - source: .github/AnVIL_Feedback_Script.sh
        dest: .github/AnVIL_Feedback_Script.sh
      - source: .github/ISSUE_TEMPLATE/course-problem-report.md
        dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      - source: .github/ISSUE_TEMPLATE/course-content-add.md
        dest: .github/ISSUE_TEMPLATE/course-content-add.md
      - source: code_of_conduct.md
        dest: code_of_conduct.md
      - source: style-sets
        dest: style-sets
      - source: assets/box_images/
        dest: assets/box_images/
      - source: assets/AnVIL_style/
        dest: assets/AnVIL_style/
        deleteOrphaned: true
      - source: assets/GDSCN_style/
        dest: assets/GDSCN_style/
        deleteOrphaned: true
      - source: assets/itcr_arrow.png
        dest: assets/itcr_arrow.png
      - source: assets/style.css
        dest: assets/style.css
      - source: assets/toc_close.css
        dest: assets/toc_close.css
      - source: config_automation.yml
        dest: config_automation.yml
  # Repositories to receive changes
    repos: |
      fhdsl/AnVIL_Book_Epigenetics_Intro
      fhdsl/AnVIL_Demos
      fhdsl/AnVIL_Outreach_Dashboard
      fhdsl/AnVIL_SRA_Data
      fhdsl/AnVIL_Urban_Genomics_PCA
      fhdsl/GDSCN_BioDIGS_AMR
      fhdsl/GDSCN_BioDIGS_Book
      fhdsl/GDSCN_BioDIGS_Soil
      fhdsl/GDSCN_SARS_RStudio_on_AnVIL
      jhudsl/AnVIL_Book_Champions
      jhudsl/AnVIL_Book_Getting_Started
      jhudsl/AnVIL_Book_Instructor_Guide
      jhudsl/AnVIL_Book_WDL
      jhudsl/AnVIL_CoFests_2024
      jhudsl/AnVIL_Phylogenetic-Techniques
      jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL
      jhudsl/GDSCN_Book_Statistics_for_Genomics_Differential_Expression
      jhudsl/GDSCN_Book_Statistics_for_Genomics_PCA
      jhudsl/GDSCN_Book_Statistics_for_Genomics_RNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq
      jhudsl/GDSCN_Book_swirl
      fhdsl/Data_on_AnVIL
      fhdsl/AnVIL_Researcher_Journey
      fhdsl/AnVIL_Data_Subsetting
      fhdsl/GDSCN_BioDIGS_BGC
###ADD NEW REPO HERE following the format above#

# AnVIL repos should sync AnVIL version of _output.yml
  - files:
      - source: _output.yml
        dest: _output.yml
    repos: |
      fhdsl/AnVIL_Book_Epigenetics_Intro
      fhdsl/AnVIL_Collection
      fhdsl/AnVIL_Data_Subsetting
      fhdsl/AnVIL_Demos
      fhdsl/AnVIL_Outreach_Dashboard
      fhdsl/AnVIL_Researcher_Journey
      fhdsl/AnVIL_SRA_Data
      fhdsl/AnVIL_Urban_Genomics_PCA

# GDSCN repos should sync the GDSCN version of _output.yml
# They should also sync the top level assets into an AnVIL style-set
  - files:
      - source: style-sets/GDSCN/_output.yml
        dest: _output.yml
      - source: _output.yml
        dest: style-sets/AnVIL/_output.yml
      - source: index.Rmd
        dest: style-sets/AnVIL/index.Rmd
    repos: |
      fhdsl/GDSCN_BioDIGS_AMR
      fhdsl/GDSCN_BioDIGS_Book
      fhdsl/GDSCN_BioDIGS_Soil
      fhdsl/GDSCN_SARS_RStudio_on_AnVIL
      jhudsl/GDSCN_Template_Test
      fhdsl/GDSCN_BioDIGS_BGC

# Repos where Hopkins took the lead have JHU branding instead of Hutch
  - files:
      - source: style-sets/AnVIL_JHU/_output.yml
        dest: _output.yml
      - source: _output.yml
        dest: style-sets/AnVIL/_output.yml
      - source: index.Rmd
        dest: style-sets/AnVIL/index.Rmd
    repos: |
      jhudsl/AnVIL_Book_Champions
      jhudsl/AnVIL_Book_Getting_Started
      jhudsl/AnVIL_Book_Instructor_Guide
      jhudsl/AnVIL_Book_WDL
      jhudsl/AnVIL_CoFests_2024
      jhudsl/AnVIL_Phylogenetic-Techniques

  - files:
      - source: style-sets/GDSCN_JHU/_output.yml
        dest: _output.yml
      - source: _output.yml
        dest: style-sets/AnVIL/_output.yml
      - source: index.Rmd
        dest: style-sets/AnVIL/index.Rmd
    repos: |
      jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL
      jhudsl/GDSCN_Book_Statistics_for_Genomics_Differential_Expression
      jhudsl/GDSCN_Book_Statistics_for_Genomics_PCA
      jhudsl/GDSCN_Book_Statistics_for_Genomics_RNA-seq
      jhudsl/GDSCN_Book_Statistics_for_Genomics_scRNA-seq
      jhudsl/GDSCN_Book_swirl


