# What are CoFests!?

CollaborationFests!, also known as **CoFests!** (and sometimes as "hackathons"), are collaborative work events where we expand and improve the AnVIL community and the AnVIL ecosystem.
Sometimes these gatherings are focused on AnVIL, and sometimes they are part of larger communities.

* *Modified from <https://galaxyproject.org/events/cofests>*

## What's in a name: CollaborationFests! and Hackathons {- .unlisted}

We collaborate.

AnVIL collaborative events are emphatically called CollaborationFests! rather than Hackathons.
Putting **Collaboration** in the name emphasizes what the events are about for us, and **Fest** communicates that they are fun events (which they are).

"Hackathon" implies an emphasis on code.
CoFests! are about contributing and learning how to contribute to all aspects of AnVIL, including training material, community infrastructure, documentation, unit tests, bug reports, and yes, even code.
First and foremost AnVIL CoFests! are about growing the community of future contributors.

* *Idea inspiration from [[GCC2024](https://galaxyproject.org/events/gcc2024/cofest)][[GCC2018](https://galaxyproject.org/events/gccbosc2018/collaboration)]*
* *Reporting inspiration from [[BioC2018](https://bioconductor.github.io/BiocWorkshops)][[BioC2020](http://bioc2020.bioconductor.org/workshops.html)][[BioC2023](https://bioc2023.bioconductor.org/workshops/)]*
