::: {.warning}
#### Controlled-Access Data {-}

Working with Controlled-Access Data (such as GTEx or dbGaP data) **requires** that you use an institutional email to comply with NIH data security requirements. Unaffiliated email accounts (such as gmail.com) **CANNOT** be given access. If you will be working with Controlled-Access Data, you should follow the appropriate option below for using your institutional email address.
:::

There are 2 ways to set up a Google account for use with Terra:

1. **Institutional Account**: use your institutional e-mail
    - If your institution uses G Suite, you can sign into Terra directly using your institutional Google account.
    - If your institution does not use G Suite, you can create a Google account that is associated with your non-Google institutional email address by following [these instructions](https://support.terra.bio/hc/en-us/articles/360029186611).
1. **Unaffiliated Google Account**: use a personal account
    - If you have an existing Google account (such as gmail.com), you can use it to sign into Terra.
    - If you do not already have a Google account that you would like to use for accessing Terra, [create one now](https://accounts.google.com/SignUp).

::: {.warning}
#### Transferring Accounts {-}

Note that there is no way for you to transfer your Terra account to a new Google account (if, for example, you change institutions). You will have to set up a new account. So, if you are *not* going to be working with Controlled-Access Data, it may be more convenient to use an unaffiliated gmail account.
:::
